/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.twigasoft.main;

import com.twigasoft.utils.DataUtils;
import com.twigasoft.utils.Database;
import com.twigasoft.utils.NumUtils;
import com.twigasoft.utils.FormUtils;
import com.twigasoft.utils.SalesUtils;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Victor
 */
public class Pay extends javax.swing.JDialog {

    /**
     * Creates new form Pay
     */
    int total;
    MainApp app;
    JTextField field = null;
    private int receipt_no;
    private int cash_sales_no;
    private int debit_sales_no;
    private int credit_sales_no;
    private int gift_card_sales_no;
    private int cheque_sales_no;
    private int mpesa_sales_no;
    private int totals;
    private int paid;

    public Pay(MainApp app, boolean modal, int total) {
        super(app, modal);
        initComponents();
        this.total = total;
        this.app = app;
        txtTotal.setText(NumUtils.formatAmount(Integer.toString(total)));
        tabMain.addTab("<html>CASH PAY<p align=center><img src=\"" + getClass().getResource("/com/twigasoft/images/cash.png") + "\"></p></html>", pnlCash);
        tabMain.addTab("<html>DEBIT CARD<p align=center><img src=\"" + getClass().getResource("/com/twigasoft/images/debit_card.png") + "\"></p></html>", pnlDebit);
        tabMain.addTab("<html>CREDIT CARD<p align=center><img src=\"" + getClass().getResource("/com/twigasoft/images/master_card.png") + "\"></p></html>", pnlCredit);
        tabMain.addTab("<html>GIFT CARD<p align=center><img src=\"" + getClass().getResource("/com/twigasoft/images/credit_card.png") + "\"></p></html>", pnlGift);
        tabMain.addTab("<html>CHEQUE<p align=center><img src=\"" + getClass().getResource("/com/twigasoft/images/cheque.png") + "\"></p></html>", pnlChaque);
        tabMain.addTab("<html>M-PESA<p align=center><img src=\"" + getClass().getResource("/com/twigasoft/images/mpesa.png") + "\"></p></html>", pnllMpesa);
        txtCash.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tabMain = new javax.swing.JTabbedPane();
        pnlCash = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        txtCash = new javax.swing.JTextField();
        txtChangeCash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlDebit = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtDebit = new javax.swing.JTextField();
        txtChangeDebit = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlCredit = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        txtCredit = new javax.swing.JTextField();
        txtChangeCredit = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnlGift = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        txtGift = new javax.swing.JTextField();
        txtChangeGift = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlChaque = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        txtCheck = new javax.swing.JTextField();
        txtChangeChaque = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnllMpesa = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        txtMpesa = new javax.swing.JTextField();
        txtChangeMpesa = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        touchPad1 = new com.twigasoft.keypads.TouchPay();
        jPanel1 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                Graphics2D g2d = (Graphics2D) grphcs;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
                GradientPaint gp = new GradientPaint(0, 0,
                    getBackground().brighter(), 0, getHeight(),
                    getBackground().darker());
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight()/2);

            }
        };
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Checkout");

        mainPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        mainPanel.setToolTipText("");

        tabMain.setBackground(new java.awt.Color(204, 204, 204));
        tabMain.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        tabMain.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabMain.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tabMain.setOpaque(true);
        tabMain.setPreferredSize(new java.awt.Dimension(262, 140));
        tabMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMainMouseClicked(evt);
            }
        });
        tabMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabMainStateChanged(evt);
            }
        });

        pnlCash.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBorder(new javax.swing.border.MatteBorder(null));

        txtCash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCash.setText("0.00");
        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });
        txtCash.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCashFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCashFocusLost(evt);
            }
        });
        txtCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCashKeyTyped(evt);
            }
        });

        txtChangeCash.setEditable(false);
        txtChangeCash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChangeCash.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtChangeCash.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Change:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Amount:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCash, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(txtChangeCash))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCash, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeCash, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout pnlCashLayout = new javax.swing.GroupLayout(pnlCash);
        pnlCash.setLayout(pnlCashLayout);
        pnlCashLayout.setHorizontalGroup(
            pnlCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCashLayout.setVerticalGroup(
            pnlCashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCashLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        tabMain.addTab("<html>CASH PAY<p><p></html>", pnlCash);

        pnlDebit.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBorder(new javax.swing.border.MatteBorder(null));

        txtDebit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDebit.setText("0.00");
        txtDebit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDebitActionPerformed(evt);
            }
        });
        txtDebit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDebitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDebitFocusLost(evt);
            }
        });

        txtChangeDebit.setEditable(false);
        txtChangeDebit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChangeDebit.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Amount:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Change:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDebit, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(txtChangeDebit))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDebit, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeDebit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDebitLayout = new javax.swing.GroupLayout(pnlDebit);
        pnlDebit.setLayout(pnlDebitLayout);
        pnlDebitLayout.setHorizontalGroup(
            pnlDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDebitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDebitLayout.setVerticalGroup(
            pnlDebitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDebitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        tabMain.addTab("<html>DEBIT CARD<p><p></html>", pnlDebit);

        pnlCredit.setBackground(new java.awt.Color(255, 255, 255));

        jPanel17.setBorder(new javax.swing.border.MatteBorder(null));

        txtCredit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCredit.setText("0.00");
        txtCredit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCreditFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCreditFocusLost(evt);
            }
        });

        txtChangeCredit.setEditable(false);
        txtChangeCredit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChangeCredit.setFocusable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Amount:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Change:");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCredit)
                    .addComponent(txtChangeCredit, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCreditLayout = new javax.swing.GroupLayout(pnlCredit);
        pnlCredit.setLayout(pnlCreditLayout);
        pnlCreditLayout.setHorizontalGroup(
            pnlCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCreditLayout.setVerticalGroup(
            pnlCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        tabMain.addTab("<html>CREDIT CARD<p><p></html>", pnlCredit);

        pnlGift.setBackground(new java.awt.Color(255, 255, 255));

        jPanel18.setBorder(new javax.swing.border.MatteBorder(null));

        txtGift.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGift.setText("0.00");
        txtGift.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtGiftFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGiftFocusLost(evt);
            }
        });

        txtChangeGift.setEditable(false);
        txtChangeGift.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChangeGift.setFocusable(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Amount:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Change:");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGift)
                    .addComponent(txtChangeGift, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGift, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeGift, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlGiftLayout = new javax.swing.GroupLayout(pnlGift);
        pnlGift.setLayout(pnlGiftLayout);
        pnlGiftLayout.setHorizontalGroup(
            pnlGiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlGiftLayout.setVerticalGroup(
            pnlGiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiftLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        tabMain.addTab("<html>GIFT CARD<p><p></html>", pnlGift);

        pnlChaque.setBackground(new java.awt.Color(255, 255, 255));
        pnlChaque.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        jPanel19.setBorder(new javax.swing.border.MatteBorder(null));

        txtCheck.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCheck.setText("0.00");
        txtCheck.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCheckFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCheckFocusLost(evt);
            }
        });

        txtChangeChaque.setEditable(false);
        txtChangeChaque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChangeChaque.setFocusable(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Amount:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Change:");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCheck)
                    .addComponent(txtChangeChaque, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeChaque, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlChaqueLayout = new javax.swing.GroupLayout(pnlChaque);
        pnlChaque.setLayout(pnlChaqueLayout);
        pnlChaqueLayout.setHorizontalGroup(
            pnlChaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlChaqueLayout.setVerticalGroup(
            pnlChaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        tabMain.addTab("<html>CHEQUE<p><p></html>", pnlChaque);

        pnllMpesa.setBackground(new java.awt.Color(255, 255, 255));
        pnllMpesa.setAlignmentX(1.0F);
        pnllMpesa.setAlignmentY(1.0F);

        jPanel20.setBorder(new javax.swing.border.MatteBorder(null));

        txtMpesa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMpesa.setText("0.00");
        txtMpesa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMpesaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMpesaFocusLost(evt);
            }
        });

        txtChangeMpesa.setEditable(false);
        txtChangeMpesa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtChangeMpesa.setFocusable(false);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Amount:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Change:");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMpesa)
                    .addComponent(txtChangeMpesa, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMpesa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtChangeMpesa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnllMpesaLayout = new javax.swing.GroupLayout(pnllMpesa);
        pnllMpesa.setLayout(pnllMpesaLayout);
        pnllMpesaLayout.setHorizontalGroup(
            pnllMpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllMpesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnllMpesaLayout.setVerticalGroup(
            pnllMpesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnllMpesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        tabMain.addTab("<html>M-PESA<p><p></html>", pnllMpesa);

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setText("Save Only");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        btnSave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSaveFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSaveFocusLost(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPrint.setText("Save & Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancel)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total:");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(255, 0, 0));
        txtTotal.setText("0.00");
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        touchPad1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(touchPad1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(touchPad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(1, 119, 164));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("  Payment For Goods");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCashFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashFocusGained
        txtCash.setText(NumUtils.removeSignStr(txtCash.getText(), ','));
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtCash.selectAll();
            }
        });
    }//GEN-LAST:event_txtCashFocusGained

    private void txtCashFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCashFocusLost
        txtChangeCash.setText(getBalChange(txtCash));
        if (txtCash.getText().equals("")) {//Defaults the text when empty
            txtCash.setText("0.00");
        } else {//Avoid errors in parsing from int to double(Currency Format.)
            txtCash.setText(NumUtils.formatAmount(NumUtils.removeSignStr(txtCash.getText(), ',')));
        }
    }//GEN-LAST:event_txtCashFocusLost

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if (getTextField().getText().equals("0.00")) {
            JOptionPane.showMessageDialog(this, "No Payments Made!", "", 1);
            getTextField().requestFocus();
        } else if (NumUtils.removeSignInt(getTextField().getText(), ',') >= total) {
            saveSoldItems();
            app.btnCancel.setEnabled(false);
            app.txtSearch.setEnabled(false);
            app.tblMain.setEnabled(false);
            app.btnTender.setEnabled(false);
            app.btnHold.setEnabled(false);
            app.btnNew.requestFocus();
            app.blinkChange(getChangeField().getText());
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "The Goods Have Been Underpaid!", "", 1);
            getTextField().requestFocus();
        }
        app.editable = false;

    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        txtChangeCash.setText(getBalChange(txtCash));
        btnSave.requestFocus();
    }//GEN-LAST:event_txtCashActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        btnSave.doClick();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed

    }//GEN-LAST:event_txtTotalActionPerformed

    private void txtCashKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCashKeyTyped
        FormUtils.validateInteger(evt);
    }//GEN-LAST:event_txtCashKeyTyped

    private void btnSaveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusGained

    }//GEN-LAST:event_btnSaveFocusGained

    private void btnSaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusLost

    }//GEN-LAST:event_btnSaveFocusLost

    private void tabMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMainMouseClicked
        int index = tabMain.getSelectedIndex();
        if (index == 0) {
            txtCash.requestFocus();
        } else if (index == 1) {
            txtDebit.requestFocus();
        } else if (index == 2) {
            txtCredit.requestFocus();
        } else if (index == 3) {
            txtGift.requestFocus();
        } else if (index == 4) {
            txtCheck.requestFocus();
        } else if (index == 5) {
            txtMpesa.requestFocus();
        }

    }//GEN-LAST:event_tabMainMouseClicked

    private void txtDebitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDebitFocusGained
        txtDebit.setText(NumUtils.removeSignStr(txtDebit.getText(), ','));
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtDebit.selectAll();
            }
        });
    }//GEN-LAST:event_txtDebitFocusGained

    private void txtCreditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditFocusGained
        txtCredit.setText(NumUtils.removeSignStr(txtCredit.getText(), ','));
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtCredit.selectAll();
            }
        });
    }//GEN-LAST:event_txtCreditFocusGained

    private void txtGiftFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiftFocusGained
        txtGift.setText(NumUtils.removeSignStr(txtGift.getText(), ','));
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtGift.selectAll();
            }
        });
    }//GEN-LAST:event_txtGiftFocusGained

    private void txtCheckFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckFocusGained
        txtCheck.setText(NumUtils.removeSignStr(txtCheck.getText(), ','));
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtCheck.selectAll();
            }
        });
    }//GEN-LAST:event_txtCheckFocusGained

    private void txtMpesaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMpesaFocusGained
        txtMpesa.setText(NumUtils.removeSignStr(txtMpesa.getText(), ','));
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                txtMpesa.selectAll();
            }
        });
    }//GEN-LAST:event_txtMpesaFocusGained

    private void txtDebitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDebitFocusLost
        txtChangeDebit.setText(getBalChange(txtDebit));
        if (txtDebit.getText().equals("")) {//Defaults the text when empty
            txtDebit.setText("0.00");
        } else {//Avoid errors in parsing from int to double(Currency Format.)
            txtDebit.setText(NumUtils.formatAmount(NumUtils.removeSignStr(txtDebit.getText(), ',')));
        }
    }//GEN-LAST:event_txtDebitFocusLost

    private void txtDebitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDebitActionPerformed
        txtChangeDebit.setText(getBalChange(txtDebit));
        btnSave.requestFocus();
    }//GEN-LAST:event_txtDebitActionPerformed

    private void txtCreditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCreditFocusLost
        txtChangeCredit.setText(getBalChange(txtCredit));
        if (txtCredit.getText().equals("")) {//Defaults the text when empty
            txtCredit.setText("0.00");
        } else {//Avoid errors in parsing from int to double(Currency Format.)
            txtCredit.setText(NumUtils.formatAmount(NumUtils.removeSignStr(txtCredit.getText(), ',')));
        }
    }//GEN-LAST:event_txtCreditFocusLost

    private void txtGiftFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiftFocusLost
        txtChangeGift.setText(getBalChange(txtGift));
        if (txtGift.getText().equals("")) {//Defaults the text when empty
            txtGift.setText("0.00");
        } else {//Avoid errors in parsing from int to double(Currency Format.)
            txtGift.setText(NumUtils.formatAmount(NumUtils.removeSignStr(txtGift.getText(), ',')));
        }
    }//GEN-LAST:event_txtGiftFocusLost

    private void txtCheckFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCheckFocusLost
        txtChangeChaque.setText(getBalChange(txtCheck));
        if (txtCheck.getText().equals("")) {//Defaults the text when empty
            txtCheck.setText("0.00");
        } else {//Avoid errors in parsing from int to double(Currency Format.)
            txtCheck.setText(NumUtils.formatAmount(NumUtils.removeSignStr(txtCheck.getText(), ',')));
        }
    }//GEN-LAST:event_txtCheckFocusLost

    private void txtMpesaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMpesaFocusLost
        txtChangeMpesa.setText(getBalChange(txtMpesa));
        if (txtMpesa.getText().equals("")) {//Defaults the text when empty
            txtMpesa.setText("0.00");
        } else {//Avoid errors in parsing from int to double(Currency Format.)
            txtMpesa.setText(NumUtils.formatAmount(NumUtils.removeSignStr(txtMpesa.getText(), ',')));
        }
    }//GEN-LAST:event_txtMpesaFocusLost

    private void tabMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabMainStateChanged
        int index = tabMain.getSelectedIndex();
        if (index == 0) {
            txtCash.requestFocus();
            clearFields();
        } else if (index == 1) {
            txtDebit.requestFocus();
            clearFields();
        } else if (index == 2) {
            txtCredit.requestFocus();
            clearFields();
        } else if (index == 3) {
            txtGift.requestFocus();
            clearFields();
        } else if (index == 4) {
            txtCheck.requestFocus();
            clearFields();
        } else if (index == 5) {
            txtMpesa.requestFocus();
            clearFields();
        }

    }//GEN-LAST:event_tabMainStateChanged
    public String getBalChange(JTextField field) {
        if (field.getText().equals("")) {
            field.setText("0.00");
        }
        if (NumUtils.removeSignInt(field.getText(), ',') >= total) {
            int value = NumUtils.removeSignInt(field.getText(), ',') - total;
            return NumUtils.formatAmount(Integer.toString(value));
        } else {
            return "";
        }
    }

    public void saveSoldItems() {
        int index = tabMain.getSelectedIndex();
        if (index == 0) {
            receipt_no = SalesUtils.getIndexNo("receipt_no");
            cash_sales_no = SalesUtils.getIndexNo("cash_sales_no");
            total = NumUtils.removeSignInt(txtTotal.getText(), ',');
            paid = NumUtils.removeSignInt(txtCash.getText(), ',');
            Object[][] data = getTableData(app.tblMain);
            createTransaction(1);
            storeItems(data);
        } else if (index == 1) {
            receipt_no = SalesUtils.getIndexNo("receipt_no");
            debit_sales_no = SalesUtils.getIndexNo("debit_sales_no");
            total = NumUtils.removeSignInt(txtTotal.getText(), ',');
            paid = NumUtils.removeSignInt(txtDebit.getText(), ',');
            Object[][] data = getTableData(app.tblMain);
            createTransaction(2);
            storeItems(data);
        } else if (index == 2) {
            receipt_no = SalesUtils.getIndexNo("receipt_no");
            credit_sales_no = SalesUtils.getIndexNo("credit_sales_no");
            total = NumUtils.removeSignInt(txtTotal.getText(), ',');
            paid = NumUtils.removeSignInt(txtCredit.getText(), ',');
            Object[][] data = getTableData(app.tblMain);
            createTransaction(3);
            storeItems(data);
        } else if (index == 3) {
            receipt_no = SalesUtils.getIndexNo("receipt_no");
            gift_card_sales_no = SalesUtils.getIndexNo("gift_card_no");
            total = NumUtils.removeSignInt(txtTotal.getText(), ',');
            paid = NumUtils.removeSignInt(txtGift.getText(), ',');
            Object[][] data = getTableData(app.tblMain);
            createTransaction(4);
            storeItems(data);
        } else if (index == 4) {
            receipt_no = SalesUtils.getIndexNo("receipt_no");
            cheque_sales_no = SalesUtils.getIndexNo("chaque_sales_no");
            total = NumUtils.removeSignInt(txtTotal.getText(), ',');
            paid = NumUtils.removeSignInt(txtCheck.getText(), ',');
            Object[][] data = getTableData(app.tblMain);
            createTransaction(5);
            storeItems(data);
        } else if (index == 5) {
            receipt_no = SalesUtils.getIndexNo("receipt_no");
            mpesa_sales_no = SalesUtils.getIndexNo("mpesa_sale_no");
            total = NumUtils.removeSignInt(txtTotal.getText(), ',');
            paid = NumUtils.removeSignInt(txtMpesa.getText(), ',');
            Object[][] data = getTableData(app.tblMain);
            createTransaction(6);
            storeItems(data);
        }
    }

    public Object[][] getTableData(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
        for (int i = 0; i < nRow; i++) {
            for (int j = 0; j < nCol; j++) {
                tableData[i][j] = dtm.getValueAt(i, j);
            }
        }
        return tableData;
    }

    public void createTransaction(int payMode) {
        Connection conn = null;
        PreparedStatement pst = null;
        String sql = "INSERT INTO tbl_sales_transactions"
                + "(receipt_no, till_no, emp_id, overall_discount, "
                + "payment_mode, total, paid, create_time) VALUES(?,?,?,?,?,?,?,?)";
        try {
            conn = Database.getConnection();
            pst = conn.prepareStatement(sql);
            pst.setInt(1, receipt_no);//receipt no
            pst.setInt(2, app.getTillNo());//till no
            pst.setInt(3, app.getEmpId());
            pst.setInt(4, NumUtils.removeSignInt(app.txtDisc.getText(), '%'));//overall disc
            pst.setInt(5, payMode);//pay mode
            pst.setInt(6, total);//total
            pst.setInt(7, paid);//paid
            pst.setObject(8, new Timestamp(new Date().getTime()));//create_time
            pst.executeUpdate();
        } catch (SQLException e) {
             Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, e);
        }
        try {
            finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void storeItems(Object[][] obj) {
        Connection conn = null;
        PreparedStatement pst = null;
        String sql = "INSERT INTO tbl_sales_sold_items"
                + "(upc_code, description, qty, discount, subtotal, receipt_id) VALUES(?,?,?,?,?,?)";
        int receipt_id = DataUtils.getReceiptId(receipt_no);
        try {
            conn = Database.getConnection();
            pst = conn.prepareStatement(sql);
            for (int i = 0; i < obj.length; i++) {
                pst.setObject(1, obj[i][0]);
                pst.setObject(2, obj[i][1]);
                pst.setObject(3, obj[i][2]);
                pst.setObject(4, NumUtils.removeSignInt(obj[i][3].toString(), '%'));
                pst.setObject(5, NumUtils.removeSignInt(obj[i][5].toString(), ','));
                pst.setObject(6, receipt_id);
                pst.executeUpdate();
            }
        } catch (SQLException e) {
                Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, e);
        }
        try {
            finalize();
        } catch (Throwable ex) {
            Logger.getLogger(Pay.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public JTextField getTextField() {
        int index = tabMain.getSelectedIndex();
        if (index == 0) {
            return txtCash;
        } else if (index == 1) {
            return txtDebit;
        } else if (index == 2) {
            return txtCredit;
        } else if (index == 3) {
            return txtGift;
        } else if (index == 4) {
            return txtCheck;
        } else {
            return txtMpesa;
        }
    }

    public JTextField getChangeField() {
        int index = tabMain.getSelectedIndex();
        if (index == 0) {
            return txtChangeCash;
        } else if (index == 1) {
            return txtChangeDebit;
        } else if (index == 2) {
            return txtChangeCredit;
        } else if (index == 3) {
            return txtChangeGift;
        } else if (index == 4) {
            return txtChangeChaque;
        } else {
            return txtChangeMpesa;
        }

    }

    public void clearFields() {
        txtCash.setText("0.00");
        txtDebit.setText("0.00");
        txtCredit.setText("0.00");
        txtGift.setText("0.00");
        txtCheck.setText("0.00");
        txtMpesa.setText("0.00");
        txtChangeCash.setText("");
        txtChangeDebit.setText("");
        txtChangeCredit.setText("");
        txtChangeGift.setText("");
        txtChangeChaque.setText("");
        txtChangeMpesa.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pnlCash;
    private javax.swing.JPanel pnlChaque;
    private javax.swing.JPanel pnlCredit;
    private javax.swing.JPanel pnlDebit;
    private javax.swing.JPanel pnlGift;
    private javax.swing.JPanel pnllMpesa;
    private javax.swing.JTabbedPane tabMain;
    private com.twigasoft.keypads.TouchPay touchPad1;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtChangeCash;
    private javax.swing.JTextField txtChangeChaque;
    private javax.swing.JTextField txtChangeCredit;
    private javax.swing.JTextField txtChangeDebit;
    private javax.swing.JTextField txtChangeGift;
    private javax.swing.JTextField txtChangeMpesa;
    private javax.swing.JTextField txtCheck;
    private javax.swing.JTextField txtCredit;
    private javax.swing.JTextField txtDebit;
    private javax.swing.JTextField txtGift;
    private javax.swing.JTextField txtMpesa;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
