/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.twigasoft.settings;

import com.twigasoft.main.MainApp;
import com.twigasoft.utils.NumUtils;
import com.twigasoft.utils.Database;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;

/**
 *
 * @author Victor
 */
public class StartDay extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     *
     * @param app
     * @param modal
     */
    MainApp app = null;

    public StartDay(MainApp app, boolean modal) {
        super(app, modal);
        this.app = app;
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/twigasoft/icons/16x16.png")));
        lblDate.setText(new SimpleDateFormat("dd MMM, yyyy").format(new Date().getTime()));
        lblTime.setText(new SimpleDateFormat("HH:mm").format(new Date().getTime()) + " Hours");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt500 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt200 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt20 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt50 = new javax.swing.JTextField();
        txt100 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt40 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt1000 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTotal = new javax.swing.JTextField();
        btnCalculate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCancel = new javax.swing.JButton();
        txtStart = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTime = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel(){
            @Override
            protected void paintComponent(Graphics grphcs) {
                super.paintComponent(grphcs);
                Graphics2D g2d = (Graphics2D) grphcs;
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
                GradientPaint gp = new GradientPaint(0, 0,
                    getBackground().brighter(), 0, getHeight(),
                    getBackground().darker());
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, getWidth(), getHeight()/2);

            }
        };
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Opening of Day Cash Registration");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        txt500.setText("0");
        txt500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt500ActionPerformed(evt);
            }
        });
        txt500.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt500FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt500FocusLost(evt);
            }
        });
        txt500.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt500KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt500KeyReleased(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("50:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("200:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("10:");

        txt5.setText("0");
        txt5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt5FocusLost(evt);
            }
        });
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt5KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("1000:");

        txt200.setText("0");
        txt200.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt200FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt200FocusLost(evt);
            }
        });
        txt200.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt200KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt200KeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("40:");

        txt20.setText("0");
        txt20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt20FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt20FocusLost(evt);
            }
        });
        txt20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt20KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt20KeyReleased(evt);
            }
        });

        txt10.setText("0");
        txt10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt10FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt10FocusLost(evt);
            }
        });
        txt10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt10KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt10KeyReleased(evt);
            }
        });

        txt50.setText("0");
        txt50.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt50FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt50FocusLost(evt);
            }
        });
        txt50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt50KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt50KeyReleased(evt);
            }
        });

        txt100.setText("0");
        txt100.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt100FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt100FocusLost(evt);
            }
        });
        txt100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt100KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt100KeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("1:");

        txt40.setText("0");
        txt40.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt40FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt40FocusLost(evt);
            }
        });
        txt40.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt40KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt40KeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("5:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("20:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("500:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("100:");

        txt1000.setText("0");
        txt1000.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt1000FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt1000FocusLost(evt);
            }
        });
        txt1000.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1000KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1000KeyReleased(evt);
            }
        });

        txt1.setText("0");
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt1FocusLost(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1KeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("NOTES");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("COINS");

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTotalMouseClicked(evt);
            }
        });
        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCalculate.setText("Calculate Total");
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt50, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(txt100)
                                .addComponent(txt1000, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt500, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt200))
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt1)
                            .addComponent(txt5)
                            .addComponent(jLabel13)
                            .addComponent(txt40)
                            .addComponent(txt20)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCancel.setText("Cancel");
        txtCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelActionPerformed(evt);
            }
        });

        txtStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtStart.setText("Start Day");
        txtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtStart)
                .addGap(18, 18, 18)
                .addComponent(txtCancel)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(txtStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTime.setText("1400Hrs");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("DATE:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("TIME:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTime)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(lblTime)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(8, 131, 160));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("  Opening of Day Procedures");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelActionPerformed
        dispose();
    }//GEN-LAST:event_txtCancelActionPerformed

    private void txtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartActionPerformed
        calculateTotal();
        Connection conn = null;
        PreparedStatement pst = null;
        String sql = "INSERT INTO tbl_startday VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try {
            conn = Database.getConnection();
            pst = conn.prepareStatement(sql);
            pst.setInt(1, 0);
            pst.setInt(2, Integer.parseInt(txt1000.getText()));
            pst.setInt(3, Integer.parseInt(txt500.getText()));
            pst.setInt(4, Integer.parseInt(txt200.getText()));
            pst.setInt(5, Integer.parseInt(txt100.getText()));
            pst.setInt(6, Integer.parseInt(txt50.getText()));
            pst.setInt(7, Integer.parseInt(txt40.getText()));
            pst.setInt(8, Integer.parseInt(txt20.getText()));
            pst.setInt(9, Integer.parseInt(txt10.getText()));
            pst.setInt(10, Integer.parseInt(txt5.getText()));
            pst.setInt(11, Integer.parseInt(txt1.getText()));
            pst.setInt(12, NumUtils.removeSignInt(txtTotal.getText(), ','));
            pst.setInt(13, app.getEmpId());
            pst.setObject(14, new Timestamp(new Date().getTime()));
            pst.setInt(15, app.getTillNo());
            pst.executeUpdate();
            dispose();
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(StartDay.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_txtStartActionPerformed
    public void selectAll(final JTextField field) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                field.selectAll();
            }
        });
    }

    private void txt1000FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1000FocusGained
        selectAll(txt1000);
    }//GEN-LAST:event_txt1000FocusGained

    private void txt500FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt500FocusGained
        selectAll(txt500);
    }//GEN-LAST:event_txt500FocusGained

    private void txt200FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt200FocusGained
        selectAll(txt200);
    }//GEN-LAST:event_txt200FocusGained

    private void txt100FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt100FocusGained
        selectAll(txt100);
    }//GEN-LAST:event_txt100FocusGained

    private void txt50FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt50FocusGained
        selectAll(txt50);
    }//GEN-LAST:event_txt50FocusGained

    private void txt40FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt40FocusGained
        selectAll(txt40);
    }//GEN-LAST:event_txt40FocusGained

    private void txt20FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt20FocusGained
        selectAll(txt20);
    }//GEN-LAST:event_txt20FocusGained

    private void txt10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt10FocusGained
        selectAll(txt10);
    }//GEN-LAST:event_txt10FocusGained

    private void txt5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt5FocusGained
        selectAll(txt5);
    }//GEN-LAST:event_txt5FocusGained

    private void txt1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1FocusGained
        selectAll(txt1);
    }//GEN-LAST:event_txt1FocusGained

    private void txt1000FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1000FocusLost
        if (txt1000.getText().equals("")) {
            txt1000.setText("0");
        }

    }//GEN-LAST:event_txt1000FocusLost

    private void txt500FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt500FocusLost
        if (txt500.getText().equals("")) {
            txt500.setText("0");
        }

    }//GEN-LAST:event_txt500FocusLost

    private void txt200FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt200FocusLost
        if (txt200.getText().equals("")) {
            txt200.setText("0");
        }

    }//GEN-LAST:event_txt200FocusLost

    private void txt100FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt100FocusLost
        if (txt100.getText().equals("")) {
            txt100.setText("0");
        }

    }//GEN-LAST:event_txt100FocusLost

    private void txt50FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt50FocusLost
        if (txt50.getText().equals("")) {
            txt50.setText("0");
        }

    }//GEN-LAST:event_txt50FocusLost

    private void txt40FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt40FocusLost
        if (txt40.getText().equals("")) {
            txt40.setText("0");
        }

    }//GEN-LAST:event_txt40FocusLost

    private void txt20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt20FocusLost
        if (txt20.getText().equals("")) {
            txt20.setText("0");
        }

    }//GEN-LAST:event_txt20FocusLost

    private void txt10FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt10FocusLost
        if (txt10.getText().equals("")) {
            txt10.setText("0");
        }

    }//GEN-LAST:event_txt10FocusLost

    private void txt5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt5FocusLost
        if (txt5.getText().equals("")) {
            txt5.setText("0");
        }

    }//GEN-LAST:event_txt5FocusLost

    private void txt1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt1FocusLost
        if (txt1.getText().equals("")) {
            txt1.setText("0");
        }

    }//GEN-LAST:event_txt1FocusLost

    private void txtTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTotalMouseClicked

    }//GEN-LAST:event_txtTotalMouseClicked

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
        calculateTotal();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void txt1000KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1000KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt500.requestFocus();
        }
    }//GEN-LAST:event_txt1000KeyPressed

    private void txt500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt500ActionPerformed

    private void txt500KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt500KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt200.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt1000.requestFocus();

        }
    }//GEN-LAST:event_txt500KeyPressed

    private void txt200KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt200KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt100.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt500.requestFocus();
        }
    }//GEN-LAST:event_txt200KeyPressed

    private void txt100KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt100KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt200.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt50.requestFocus();
        }
    }//GEN-LAST:event_txt100KeyPressed

    private void txt50KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt100.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt40.requestFocus();
        }
    }//GEN-LAST:event_txt50KeyPressed

    private void txt40KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt40KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt50.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt20.requestFocus();
        }
    }//GEN-LAST:event_txt40KeyPressed

    private void txt20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt40.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt10.requestFocus();
        }
    }//GEN-LAST:event_txt20KeyPressed

    private void txt10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt10KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt20.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt5.requestFocus();
        }
    }//GEN-LAST:event_txt10KeyPressed

    private void txt5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt10.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txt1.requestFocus();
        }
    }//GEN-LAST:event_txt5KeyPressed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed

    }//GEN-LAST:event_txt1ActionPerformed

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txt5.requestFocus();
        }
    }//GEN-LAST:event_txt1KeyPressed

    private void txt1000KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1000KeyReleased
        if (!txt1000.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt1000KeyReleased

    private void txt500KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt500KeyReleased
        if (!txt500.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt500KeyReleased

    private void txt200KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt200KeyReleased
        if (!txt200.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt200KeyReleased

    private void txt50KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt50KeyReleased
        if (!txt50.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt50KeyReleased

    private void txt40KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt40KeyReleased
        if (!txt40.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt40KeyReleased

    private void txt20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20KeyReleased
        if (!txt20.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt20KeyReleased

    private void txt10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt10KeyReleased
        if (!txt10.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt10KeyReleased

    private void txt5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyReleased
        if (!txt5.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt5KeyReleased

    private void txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyReleased
        if (!txt1.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt1KeyReleased

    private void txt100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt100KeyReleased
        if (!txt100.getText().equals("")) {
            btnCalculate.doClick();
        }
    }//GEN-LAST:event_txt100KeyReleased
    public void calculateTotal() {
        int total = 0;
        total = (Integer.parseInt(txt1000.getText()) * 1000) + (Integer.parseInt(txt500.getText()) * 500)
                + (Integer.parseInt(txt200.getText()) * 200) + (Integer.parseInt(txt100.getText()) * 100)
                + (Integer.parseInt(txt50.getText()) * 50) + (Integer.parseInt(txt40.getText()) * 40)
                + (Integer.parseInt(txt20.getText()) * 20) + (Integer.parseInt(txt10.getText()) * 10)
                + (Integer.parseInt(txt5.getText()) * 5) + (Integer.parseInt(txt1.getText()) * 1);
        txtTotal.setText(NumUtils.formatAmount(Integer.toString(total)));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartDay dialog = new StartDay(new MainApp(1), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt100;
    private javax.swing.JTextField txt1000;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt200;
    private javax.swing.JTextField txt40;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txt500;
    private javax.swing.JButton txtCancel;
    private javax.swing.JButton txtStart;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
